### ISSUE TITLE
default_pipeline.star does not exist in /path/to/relion/project. Skipping

### ISSUE THREAD

**Issue by ryanfeathers** [dzyla/Follow_Relion_gracefully#2]
Hi Dawid,

I'm really excited to see the new version! I tried to start it in a relion4 project but it's not able to find the default_pipeline.star file. I'm positive the file is in the main directory and that it's correctly named.

Full disclosure, I'm trying to run it in a massive project directory with a lot of clutter. Also, the pipeline was originally started in relion 3.1 and was converted to 4. Is there anything I can try to troubleshoot? Apologies if I'm missing something obvious. 

Best regards,

Ryan

**Comment by dzyla** [comment]
Hi Ryan!

Thanks for reaching out. Could you show me the command you were using to run the program? Usually, the program searches for the default_pipeline.star file inside the folders provided in the --i argument. You could also try the `ls` command inside the given folder if the default_pipeline.star is showing up. Thanks!

**Comment by ryanfeathers** [comment]
Hi Dawid,

Sure! Here is the command and output I used. 
```
(FollowRelion) [omitted Follow_Relion_gracefully]$ python follow_relion_gracefully_run.py --i /fourteen-1/ryan/02242019/
Using 4 CPUs for processing!
Processing folder 0 /fourteen-1/ryan/02242019
default_pipeline.star does not exist in /fourteen-1/ryan/02242019. Skipping...
^CExiting...
```

I'm a little hesitant to post the output of ls publicly because it's an embarrassingly long list but, to verify the file exists in the path here's more default_pipeline.star

```
(FollowRelion) [omitted Follow_Relion_gracefully]$ more /fourteen-1/ryan/02242019/default_pipeline.star 

# version 30001

data_pipeline_general

_rlnPipeLineJobCounter                    1545
 

# version 30001

data_pipeline_processes

loop_ 
_rlnPipeLineProcessName #1 
_rlnPipeLineProcessAlias #2 
_rlnPipeLineProcessTypeLabel #3 
_rlnPipeLineProcessStatusLabel #4 
Import/job008/       None relion.import  Succeeded 
MotionCorr/job009/       None relion.motioncorr  Succeeded 
CtfFind/job010/       None relion.ctffind  Succeeded 
ManualPick/job011/       None relion.manualpick  Succeeded 
AutoPick/job012/       None relion.autopick  Succeeded 
Import/job013/       None relion.import  Succeeded 
MotionCorr/job014/       None relion.motioncorr  Succeeded 
CtfFind/job015/       None relion.ctffind  Succeeded 
Extract/job016/       None relion.extract  Succeeded 
Extract/job017/       None relion.extract  Succeeded 
```
Also 

```
(FollowRelion) [omitted Follow_Relion_gracefully]$ ls /fourteen-1/ryan/02242019/d*
/fourteen-1/ryan/02242019/data_replaced.star  /fourteen-1/ryan/02242019/default_pipeline.star

```

**Comment by ryanfeathers** [comment]
Hi Dawid,

So it turns out the issue was parse errors with default_pipeline.star. I found these errors in FollowRelion.log. This project has some jobs that I used .star or .mrc files from the main project directory so in the default_pipeline.star file there were items that didn't have a relion job type sub directory.

Unfortunately my time is extremely limited right now otherwise I would look more into how to accommodate these file paths. I'll come back to it if it's still a problem in a month or so but in the meantime maybe an additional except statement could relay the parse error to the terminal? 

Thanks again!

Ryan

**Comment by dzyla** [comment]
Hi, @ryanfeathers!

Thanks for the update; this would be my next question to provide the log file. I can update the program to provide more verbose information about the problem with reading the default_pipeline.star file. Can you share the file so I have a reference?

Thank you!

**Comment by ryanfeathers** [comment]
Awesome, thank you! I emailed you the files.

Best regards,

Ryan
