### ISSUE TITLE
relion.autopick.topaz.pick FOM values

### ISSUE THREAD

**Issue by derpaule** [dzyla/Follow_Relion_gracefully#3]
Hello, 
First of all congratulations for this great tool! 
Looking at a relion.autopick.topaz.pick job, I noticed that it it is only possible to select positive FOM values for display, but these take typically negative values. Could you change the limits? 
Cheers,
Tim

**Comment by dzyla** [comment]
Hi Tim,

Thank you so much for your kind words!

Indeed, the minimum value was hard-coded to be 0. I have fixed it to reflect the minimum value from the picking statistics. Please take a look at the updated code.

Best,
Dawid
